name: LOOKER_TEST_ACTION

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install looker_sdk
        pip install jinja2
        pip install spectacles
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Action Script
      env:
        BASE_URL: ${{ secrets.L_BASE_URL }}
        CLIENT_ID: ${{ secrets.L_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.L_CLIENT_SECRET }}
        VERIFY_SSL: ${{ secrets.VERIFY_SSL }}
      run: |
       echo ${GITHUB_REF##*/}
       echo ${GITHUB_REPOSITORY##*/}
       echo ${BASE_URL}
       spectacles sql \
       --project hugo_sandbox \
       --branch master \
       --base-url https://profservices.dev.looker.com \
       --client-id b88cXDHjbkMwvbwCWXCj \
       --client-secret jbH2X6JCDJqyh2nR6HWFm3Q5 -v \
       2>&1 | tee test.txt
       
      # python .github/actions/spectacles/run_spectacles.py
      # python .github/actions/test_ini_in.py
      # python .github/actions/run_test.py
        
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "hselbie"
        git add .
        git commit -m "Updating the repository GitHub html pages in the docs folder"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}